import type { GazetteerEntry } from './index.ts';

/**
 * UK ceremonial counties (England, Wales, Scotland, NI — the ones that appear in
 * crop circle reports, which skew heavily to southern England). Aliases include
 * typos observed in the live data ("Wilshire", "Hertsfordshire"). radius ≈ √(area/π).
 */
export const ukRegions: GazetteerEntry[] = [
  { name: 'Bedfordshire', aliases: ['Beds'], lat: 52.08, lon: -0.42, radiusKm: 20 },
  { name: 'Berkshire', aliases: ['Berks'], lat: 51.45, lon: -1.05, radiusKm: 20 },
  { name: 'Bristol', aliases: [], lat: 51.45, lon: -2.58, radiusKm: 7 },
  { name: 'Buckinghamshire', aliases: ['Bucks'], lat: 51.75, lon: -0.81, radiusKm: 25 },
  { name: 'Cambridgeshire', aliases: ['Cambs'], lat: 52.3, lon: 0.05, radiusKm: 33 },
  { name: 'Cheshire', aliases: [], lat: 53.16, lon: -2.58, radiusKm: 27 },
  { name: 'Cornwall', aliases: [], lat: 50.4, lon: -4.9, radiusKm: 34 },
  { name: 'Cumbria', aliases: ['Cumberland'], lat: 54.58, lon: -2.85, radiusKm: 47 },
  { name: 'Derbyshire', aliases: [], lat: 53.1, lon: -1.6, radiusKm: 29 },
  { name: 'Devon', aliases: ['Devonshire'], lat: 50.75, lon: -3.75, radiusKm: 46 },
  { name: 'Dorset', aliases: [], lat: 50.78, lon: -2.3, radiusKm: 29 },
  { name: 'Durham', aliases: ['County Durham'], lat: 54.7, lon: -1.75, radiusKm: 26 },
  { name: 'East Sussex', aliases: [], lat: 50.93, lon: 0.25, radiusKm: 24 },
  { name: 'Essex', aliases: [], lat: 51.77, lon: 0.55, radiusKm: 34 },
  { name: 'Gloucestershire', aliases: ['Gloucs', 'Glos'], lat: 51.85, lon: -2.15, radiusKm: 29 },
  { name: 'Greater London', aliases: ['London'], lat: 51.5, lon: -0.12, radiusKm: 22 },
  { name: 'Greater Manchester', aliases: ['Manchester'], lat: 53.5, lon: -2.3, radiusKm: 20 },
  { name: 'Hampshire', aliases: ['Hants'], lat: 51.06, lon: -1.31, radiusKm: 35 },
  { name: 'Herefordshire', aliases: [], lat: 52.08, lon: -2.73, radiusKm: 26 },
  {
    name: 'Hertfordshire',
    aliases: ['Herts', 'Hertsfordshire'],
    lat: 51.81,
    lon: -0.24,
    radiusKm: 23,
  },
  { name: 'Isle of Wight', aliases: ['IOW'], lat: 50.67, lon: -1.32, radiusKm: 11 },
  { name: 'Kent', aliases: [], lat: 51.2, lon: 0.73, radiusKm: 34 },
  { name: 'Lancashire', aliases: ['Lancs'], lat: 53.8, lon: -2.6, radiusKm: 31 },
  { name: 'Leicestershire', aliases: ['Leics'], lat: 52.63, lon: -1.13, radiusKm: 26 },
  { name: 'Lincolnshire', aliases: ['Lincs'], lat: 53.1, lon: -0.2, radiusKm: 43 },
  { name: 'Merseyside', aliases: [], lat: 53.4, lon: -2.95, radiusKm: 14 },
  { name: 'Norfolk', aliases: [], lat: 52.67, lon: 0.95, radiusKm: 41 },
  { name: 'North Yorkshire', aliases: [], lat: 54.13, lon: -1.5, radiusKm: 51 },
  { name: 'Northamptonshire', aliases: ['Northants'], lat: 52.27, lon: -0.88, radiusKm: 27 },
  { name: 'Northumberland', aliases: [], lat: 55.25, lon: -2.05, radiusKm: 40 },
  { name: 'Nottinghamshire', aliases: ['Notts'], lat: 53.13, lon: -1.0, radiusKm: 26 },
  { name: 'Oxfordshire', aliases: ['Oxon'], lat: 51.76, lon: -1.27, radiusKm: 28 },
  { name: 'Rutland', aliases: [], lat: 52.65, lon: -0.65, radiusKm: 11 },
  { name: 'Shropshire', aliases: ['Salop'], lat: 52.65, lon: -2.73, radiusKm: 32 },
  { name: 'Somerset', aliases: [], lat: 51.09, lon: -2.95, radiusKm: 36 },
  { name: 'South Yorkshire', aliases: [], lat: 53.45, lon: -1.35, radiusKm: 22 },
  { name: 'Staffordshire', aliases: ['Staffs'], lat: 52.85, lon: -2.0, radiusKm: 29 },
  { name: 'Suffolk', aliases: [], lat: 52.19, lon: 1.0, radiusKm: 35 },
  { name: 'Surrey', aliases: [], lat: 51.25, lon: -0.42, radiusKm: 23 },
  {
    name: 'Sussex (unspecified)',
    aliases: ['Sussex'],
    lat: 50.95,
    lon: -0.13,
    radiusKm: 40,
  },
  { name: 'Tyne and Wear', aliases: [], lat: 54.96, lon: -1.55, radiusKm: 13 },
  { name: 'Warwickshire', aliases: ['Warks'], lat: 52.28, lon: -1.58, radiusKm: 25 },
  { name: 'West Midlands', aliases: [], lat: 52.48, lon: -1.9, radiusKm: 17 },
  { name: 'West Sussex', aliases: [], lat: 50.95, lon: -0.43, radiusKm: 25 },
  { name: 'West Yorkshire', aliases: [], lat: 53.75, lon: -1.65, radiusKm: 25 },
  {
    name: 'Wiltshire',
    aliases: ['Wilts', 'Wilshire', 'Wiltshire.'],
    lat: 51.32,
    lon: -1.95,
    radiusKm: 33,
  },
  { name: 'Worcestershire', aliases: ['Worcs'], lat: 52.2, lon: -2.2, radiusKm: 24 },
  { name: 'East Riding of Yorkshire', aliases: ['East Yorkshire', 'Humberside'], lat: 53.85, lon: -0.55, radiusKm: 31 },
  // Wales / Scotland / NI regions that appear occasionally in reports
  { name: 'Powys', aliases: [], lat: 52.35, lon: -3.4, radiusKm: 41 },
  { name: 'Gwynedd', aliases: [], lat: 52.95, lon: -3.9, radiusKm: 28 },
  { name: 'Glamorgan', aliases: ['South Glamorgan', 'Mid Glamorgan', 'West Glamorgan'], lat: 51.55, lon: -3.5, radiusKm: 26 },
  { name: 'Fife', aliases: [], lat: 56.25, lon: -3.15, radiusKm: 21 },
  { name: 'Perthshire', aliases: ['Perth and Kinross'], lat: 56.6, lon: -3.85, radiusKm: 41 },
  { name: 'Scottish Borders', aliases: ['Borders'], lat: 55.55, lon: -2.8, radiusKm: 38 },
];
